# -*- coding: utf-8 -*-
"""Task 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iLouGrMwJDFLtJrMc8loVVGQsuuuUKbJ
"""

# Import libraries
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# Connect to the SQLite database
conn = sqlite3.connect('sales_data.db')
cursor = conn.cursor()

# Create the sales table
cursor.execute("""
CREATE TABLE IF NOT EXISTS sales (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product TEXT,
    quantity INTEGER,
    price REAL
)
""")

# Insert sample data into the sales table
sample_data = [
    ('Product A', 10, 5.0),
    ('Product B', 20, 7.5),
    ('Product A', 15, 5.0),
    ('Product C', 5, 10.0),
    ('Product B', 10, 7.5)
]


# Insert data
cursor.executemany("INSERT INTO sales (product, quantity, price) VALUES (?, ?, ?)", sample_data)
conn.commit()

# Execute SQL query
query = """
SELECT product,
       SUM(quantity) AS total_qty,
       SUM(quantity * price) AS revenue
FROM sales
GROUP BY product
"""

# Load results into pandas DataFrame
df = pd.read_sql_query(query, conn)

# Print the summary table
print("Sales Summary:\n", df)

# Plot Revenue by Product - Bar Chart
plt.figure(figsize=(8,5))
df.plot(kind='bar', x='product', y='revenue', legend=False)
plt.xlabel('Product')
plt.ylabel('Total Revenue')
plt.title('Sales Revenue by Product')
plt.tight_layout()

# Save and show bar chart
plt.savefig('sales_revenue_by_product.png')
plt.show()

# Plot Revenue proportion - Pie Chart
plt.figure(figsize=(6,6))
plt.pie(df['revenue'], labels=df['product'], autopct='%1.1f%%', startangle=140)
plt.title('Revenue Distribution by Product')
plt.tight_layout()

# Save and show pie chart
plt.savefig('revenue_proportion_pie_chart.png')
plt.show()

# Close the database connection
conn.close()

